package model

data class ExportedRoiModel(
  val id: Int,
  val researchId: Int,
  val acquisitionNumber: String,
  val dcmFilename: String,
  val instanceNumber: Int,
  val seriesNumber: Int,
  val sopInstanceUid: String,
  val anatomicalLocation: String,
  val confidence: Double,
  val roiFilename: String,
  val roiShape: String,
  val roiType: String,
  val roiTypeIndex: Int,
  val taggerId: String,
  val xCenter: Double,
  val xSize: Double,
  val yCenter: Double,
  val ySize: Double,
  val text: String,
)

fun ExportedRoiModel.toExportedRoiEntity(): ExpertRoiEntity =
  ExpertRoiEntity(
    id = id,
    researchId = researchId,
    acquisitionNumber = acquisitionNumber,
    dcmFilename = dcmFilename,
    instanceNumber = instanceNumber,
    seriesNumber = seriesNumber,
    sopInstanceUid = sopInstanceUid,
    anatomicalLocation = anatomicalLocation,
    confidence = confidence,
    roiFilename = roiFilename,
    roiShape = roiShape,
    roiType = roiType,
    roiTypeIndex = roiTypeIndex,
    taggerId = taggerId,
    xCenter = xCenter,
    xSize = xSize,
    yCenter = yCenter,
    ySize = ySize,
    text = text,
  )

fun ExpertRoiEntity.toExportedRoiModel(): ExportedRoiModel =
  ExportedRoiModel(
    id = id,
    researchId = researchId,
    acquisitionNumber = acquisitionNumber,
    dcmFilename = dcmFilename,
    instanceNumber = instanceNumber,
    seriesNumber = seriesNumber,
    sopInstanceUid = sopInstanceUid,
    anatomicalLocation = anatomicalLocation,
    confidence = confidence,
    roiFilename = roiFilename,
    roiShape = roiShape,
    roiType = roiType,
    roiTypeIndex = roiTypeIndex,
    taggerId = taggerId,
    xCenter = xCenter,
    xSize = xSize,
    yCenter = yCenter,
    ySize = ySize,
    text = text,
  )