package model

fun getErrorMessageByCode(errorCode: ErrorStringCode): String {
  return when (errorCode) {
    ErrorStringCode.BASE_ERROR -> BASE_ERROR
    ErrorStringCode.USER_EXIST_ERROR -> USER_EXISTS_ERROR
    ErrorStringCode.INVALID_AUTH_CREDENTIALS -> INVALID_AUTH_CREDENTIALS
    ErrorStringCode.INVALID_REGISTER_LOGIN -> INVALID_REGISTER_LOGIN
    ErrorStringCode.INVALID_REGISTER_ROLE -> INVALID_REGISTER_ROLE
    ErrorStringCode.INVALID_REGISTER_PASSWORD -> INVALID_REGISTER_PASSWORD
    ErrorStringCode.INVALID_REGISTER_LOGIN_SIMBOLS -> INVALID_REGISTER_LOGIN_SIMBOLS
    ErrorStringCode.REGISTER_FAILED -> REGISTER_FAILED
    ErrorStringCode.USER_RESEARCHES_LIST_FAILED -> USER_RESEARCHES_LIST_FAILED
    ErrorStringCode.RESEARCH_NOT_FOUND -> RESEARCH_NOT_FOUND
    ErrorStringCode.RESEARCH_INITIALIZATION_FAILED -> RESEARCH_INITIALIZATION_FAILED
    ErrorStringCode.RESEARCH_DATA_FETCH_FAILED -> RESEARCH_DATA_FETCH_FAILED
    ErrorStringCode.SESSION_EXPIRED -> SESSION_EXPIRED
    ErrorStringCode.INCORRECT_SLICE_NUMBER -> INCORRECT_SLICE_NUMBER
    ErrorStringCode.INCORRECT_AXIAL_COORD -> INCORRECT_AXIAL_COORD
    ErrorStringCode.INCORRECT_FRONTAL_COORD -> INCORRECT_FRONTAL_COORD
    ErrorStringCode.INCORRECT_SAGITTAL_COORD -> INCORRECT_SAGITTAL_COORD
    ErrorStringCode.HOUNSFIELD_ERROR -> HOUNSFIELD_FETCH_ERROR
    ErrorStringCode.SESSION_CLOSE_FAILED -> SESSION_CLOSE_FAILED
    ErrorStringCode.GET_SLICE_FAILED -> GET_SLICE_FAILED
    ErrorStringCode.CREATE_MARK_FAILED -> CREATE_MARK_FAILED
    ErrorStringCode.NOT_INITIALIZED_YET -> NOT_INITIALIZED_YET
    ErrorStringCode.AUTH_FAILED -> AUTH_FAILED
    ErrorStringCode.UPDATE_MARK_FAILED -> MARK_UPDATE_EXCEPTION
    ErrorStringCode.GET_MARKS_FAILED -> MARKS_FETCH_EXCEPTION
    ErrorStringCode.DELETE_MARK_FAILED -> MARK_DELETE_EXCEPTION
    ErrorStringCode.RESEARCH_CLOSE_FAILED -> RESEARCH_CLOSE_FAILED
  }
}
