
const val AUTHENTICATION = "Authentication"
const val NAME_FIELD = "name"
const val PASSWORD_FIELD = "password"
const val ROLE_FIELD = "role"
const val SEEN_FIELD = "seen"
const val DONE_FIELD = "done"
const val MARKED_FIELD = "marked"
const val USER_ID_FIELD = "user_id"
const val RESEARCH_ID_FIELD = "research_id"
const val CT_TYPE_FIELD = "ct_type"
const val LEFT_PERCENT_FIELD = "left_percent"
const val RIGHT_PERCENT_FIELD = "right_percent"
const val RIGHT_UPPER_LOBE_VALUE_FIELD = "right_upper_lobe_value"
const val MIDDLE_LOBE_VALUE_FIELD = "middle_lobe_value"
const val RIGHT_LOWER_LOBE_VALUE_FIELD = "right_lower_lobe_value"
const val LEFT_UPPER_LOBE_VALUE_FIELD = "left_upper_lobe_value"
const val LEFT_LOWER_LOBE_VALUE_FIELD = "left_lower_lobe_value"

const val ACCESSION_NUMBER_FIELD = "accession_number"
const val STUDY_INSTANCE_UID_FIELD = "study_instance_uid"
const val STUDY_ID_FIELD = "study_id"
const val PROTOCOL_FIELD = "protocol"
const val ACCESSION_NUMBER_BASE_FIELD = "accession_number_base"
const val ACCESSION_NUMBER_LAST_DIGIT_FIELD = "accession_number_last_digit"
const val JSON_NAME_FIELD = "json_name"
const val DOCTOR_1_FIELD = "doctor1"
const val DOCTOR_2_FIELD = "doctor2"
const val POS_IN_BLOCK_FIELD = "pos_in_block"
const val MODALITY_FIELD = "modality"
const val CATEGORY_FIELD = "category"

const val USER_TABLE = "user"
const val RESEARCH_TABLE = "research"
const val COVID_MARKS_TABLE = "covid_marks"

const val MULTI_PLANAR_MARKS_TABLE = "multi_planar_marks"
const val PLANAR_MARKS_TABLE = "planar_marks"
const val EXPERT_MARKS_TABLE = "expert_marks"
const val X_FIELD = "x"
const val Y_FIELD = "y"
const val Z_FIELD = "z"
const val Z_MM_FIELD = "z_mm"
const val RADIUS_HORIZONTAL_FIELD = "radius_horizontal"
const val RADIUS_VERTICAL_FIELD = "radius_vertical"
const val SIZE_VERTICAL_FIELD = "size_vertical"
const val SIZE_HORIZONTAL_FIELD = "size_horizontal"
const val MARK_TYPE_FILED = "mark_type"
const val CUT_TYPE_FILED = "cut_type"
const val SHAPE_TYPE_FILED = "shape_type"
const val COMMENT_FILED = "comment"
const val DIAMETER_MM_FIELD = "diameter_mm"


const val ROOT = "/"
const val STATIC_ROUTE = "/static"
const val RESOURCE_STATIC = "static/static"
const val RESOURCE_INDEX = "static/index.html"
const val RESOURCE_JS = "js.js"
